CREATE TABLE IF NOT EXISTS balance_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_last4 VARCHAR(4) NOT NULL,
    occurred_at VARCHAR(40) NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    direction VARCHAR(6) NOT NULL,
    stated_balance DECIMAL(14,2) NOT NULL,
    source_message_id VARCHAR(200) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_balance_observations_account
ON balance_observations(account_last4, occurred_at);
